name = "Hyperparameters"
uuid = "dec02a44-0573-464b-9dcd-b0da4b5d2d2e"
authors = ["Invenia Technical Computing Corporation"]
version = "0.1.2"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
FilePathsBase = "0.6, 0.7, 0.8, 0.9"
JSON = "0.21"
Memento = "0.11, 0.12, 0.13, 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
